### ISSUE TITLE
thoughts about re-design

### ISSUE THREAD

**Issue by suchov** [kottans/kottans.github.io#104]
https://gleechat.com
https://github.com/Linrstudio/linrstudio.github.io/blob/master/app/threejs/threejs.html

**Comment by zonzujiro** [comment]
I think we should continue discussion regarding the new website.

As an example:

### As a user I would like to:

- See information about the previous courses - program, tasks, lectors, etc.
- See information about the current courses
- See information about planned courses - but this should be discussed because, usually, we don't know the date of the beginning, program, etc.
- See the list of founders and active participants
- See the list of invited mentors
- See short story about the community - we not school, we don't have regular courses, we are not paid for what we are doing, etc.
- Maybe a page with t-shirts or prints, or something like this

Also, I believe we can add some kind of "premium courses".  Like proposed by Yura Yarosh - create the separate page with information and materials about course made by one, or several, strong and well-known lectors.

**Comment by OleksiyRudenko** [comment]
* As a student I want to subscribe to a particular planned course updates

**Comment by zonzujiro** [comment]
@OleksiyRudenko source of updates? You mean some sort of email?

**Comment by OleksiyRudenko** [comment]
@OleksiyRudenko dunno. It might be a set of links to telegram chat, twitter channel, whatever. With a very clear promise that student will be kept updated on a **particular** course.

**Comment by sudodoki** [comment]
updates w/o too much trouble could be done by consistently using hashtags in twitter (like `#kottans_org #course #frontend` and just putting link to search by that in update section (or have tg channel with announces and hashtags - but there's no ability to link to it from web, maybe only if there would be pinned message in channel so new users could click it after joining)

**Comment by zonzujiro** [comment]
I think we can discuss future possibilities during the next meeting - will we make some changes at all, looking for a designer and choosing a contact person from our side for this designer. @suchov what do you think?

**Comment by suchov** [comment]
we can discuss it offline, but online the discussion should be present too.

**Comment by zonzujiro** [comment]
I think, that we should move to online when we will have shared, general view of changes and someone, who will pe contact person with a designer.

**Comment by zonzujiro** [comment]
As I see it right now:

**Several sections:**

1. Main page with general info. A short story about the community - we are not a school, we don't have regular courses, we are not paid for what we are doing, etc. List of people who most active in the general life of the community.
2. Courses - current, planned and archive with courses. Program, mentors, lectures, list of topics. Description of p2p course, FE course, maybe some backend courses which we want to make.
3. Section for strong developers who want to create own courses. Something like Yura Yarosh wanted to do for himself.
4. And a section about Kottans Development ;)

Fancy examples:
1. https://liga-a.ru/
